#server:
#  port: 6547

#google.clientId=448582532291-dqdhf6chklth334pl2pb9ui9j86d7kqh.apps.googleusercontent.com
#google.clientSecret=kkezhH7XUZw_X9vM2e5J-iiX
#google.accessTokenUri=https://www.googleapis.com/oauth2/v3/token
#google.userAuthorizationUri=https://accounts.google.com/o/oauth2/auth
#google.redirectUri=http://localhost:6547/google-login
# Usually "authorization_code"
#oauth2.tokenName=authorization_code

#security:
#  oauth2:
#    client:
#      clientId: 448582532291-dqdhf6chklth334pl2pb9ui9j86d7kqh.apps.googleusercontent.com
#      clientSecret: kkezhH7XUZw_X9vM2e5J-iiX
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#      tokenName: authorization_code
#      authenticationScheme: query
#      clientAuthenticationScheme: http
#    resource:
#      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
#    client:
#      clientId: 233668646673605
#      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me